@startuml
title Development / Package View - CJ Secure
skinparam packageStyle rectangle

package "frontend" {
  [index.html]
  [style.css]
  [script.js]
}

package "apps.routes" {
  [authRoutes.py]
  [recordroutes.py]
  [adminroutes.py]
}

package "apps.controllers" {
  [loginController.py]
  [recordController.py]
  [adminController.py]
}

package "apps.services" {
  [authSvc.py]
  [recordSvc.py]
  [mfaSvc.py]
  [accessControlSvc.py]
  [auditLogger.py]
}

package "apps.repositories" {
  [userRepo.py]
  [recordRepo.py]
  [auditRepo.py]
}

package "apps.models" {
  [user.py]
  [record.py]
  [secEvent.py]
  [permission.py]
}

package "apps.security" {
  [passHash.py]
  [mfaFactory.py]
  [mfaStrategies.py]
  [masker.py]
  [tokenizer.py]
}

[index.html] --> [script.js]
[script.js] --> [authRoutes.py]
[script.js] --> [recordroutes.py]
[script.js] --> [adminroutes.py]

[authRoutes.py] --> [loginController.py]
[recordroutes.py] --> [recordController.py]
[adminroutes.py] --> [adminController.py]

[loginController.py] --> [authSvc.py]
[recordController.py] --> [recordSvc.py]
[adminController.py] --> [auditLogger.py]
[adminController.py] --> [accessControlSvc.py]
[adminController.py] --> [userRepo.py]

[authSvc.py] --> [userRepo.py]
[authSvc.py] --> [passHash.py]
[authSvc.py] --> [mfaSvc.py]
[authSvc.py] --> [auditLogger.py]

[recordSvc.py] --> [recordRepo.py]
[recordSvc.py] --> [accessControlSvc.py]
[recordSvc.py] --> [masker.py]
[recordSvc.py] --> [tokenizer.py]
[recordSvc.py] --> [auditLogger.py]

[mfaSvc.py] --> [mfaFactory.py]
[mfaFactory.py] --> [mfaStrategies.py]

[auditLogger.py] --> [auditRepo.py]
[userRepo.py] --> [user.py]
[recordRepo.py] --> [record.py]
[auditRepo.py] --> [secEvent.py]
@enduml
